version: '3.9'

services:
  frontend:
    container_name: frontend
    image: grozzzny/kupipodariday:v1.0
    restart: always
    ports:
      - '8081:80'
    depends_on:
      backend:
        condition: service_started
  backend:
    container_name: backend
    image: grozzzny/api-kupipodariday:v1.0
    restart: always
    ports:
      - '4000:3000'
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: postgresdb
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready',
          '-q',
          '-h',
          'localhost',
          '-p',
          '${POSTGRES_PASSWORD}',
          '-U',
          '${POSTGRES_USER}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgresdata:
